### ISSUE TITLE
Mailer Error (Mobile View Issue)

### ISSUE THREAD

**Issue by divyatiwari5** [civilmachines/Rekrutify_Candidate_IssueTracker#33]
![screenshot_20180614-170813](https://user-images.githubusercontent.com/13404776/41410030-c6591ac6-6ff5-11e8-8959-56274b15c9b9.png)

Thank you for registering on ________.  "www.recrutify.com" is invisible. If we click on that blank space then it redirects to company's website but the link is not visible.

**Comment by MaaheshSharma** [comment]
Fixed
